export const reportConstants = {
  REPORTS_EARNINGS_STATS_SAGA: "REPORTS_EARNINGS_STATS_SAGA",
  EARNINGS_STATS_REQUEST: "EARNINGS_STATS_REQUEST",
  EARNINGS_STATS_RESPONSE: "EARNINGS_STATS_RESPONSE",
  REPORT_EARNINGS_STATS_API: "/jobs/candidates/earnings/stats?year=earningYear",
};
