export default myJobConstants = {
  MY_JOB_API: "jobs/applied",
  MY_JOB_SAGA: "MY_JOB_SAGA",
  MY_JOB_REQUEST: "MY_JOB_REQUEST",
  MY_JOB_RESPONSE: "MY_JOB_RESPONSE",

  MY_JOB_DESCRIPTION_API: "jobs/applied",
  MY_JOB_DESCRIPTION_SAGA: "MY_JOB_DESCRIPTION_SAGA",
  MY_JOB_DESCRIPTION_REQUEST: "MY_JOB_DESCRIPTION_REQUEST",
  MY_JOB_DESCRIPTION_RESPONSE: "MY_JOB_DESCRIPTION_RESPONSE",

  UN_APPLY_JOB_API: "jobs/jobID/unapply?userNote=UserNote",
};
