export const routes = {
  login: "/login",
  profile: "/profile",
  dashboard: "/dashboard",
  userManagement: "/user-management",
  userManagementViewVenderUser: "/user-management/:id",
  userManagementAddVendorUser: "/user-management/add",
  userManagementEditVendorUser: "/user-management/edit/:id",
  jobManagement: "/job-management",
  jobManagementDetails: "/job-management/details/:id",
  appliedJobs: "/applied-jobs",
  appliedJobsDetails: "/applied-jobs/details/:id",
  myWork: "/my-work",
  myWorkDetails: "/my-work/details/:id",
  reports: "/reports",
  earnings: "/earnings",
  faq: "/faq",
  raiseDispute: "/raise-dispute",
  askUs: "/ask-us",
  subModule: "/my-work/module/:id/submodules",
  workFlow: "/workflow-screen/:id",
  editWorkFlow: "/modules/:mid/submodules/:smid/workflow-screen/:id/form/:formId",
  notFound: "/not-found",
};
