export const LOADER_ON = "LOADER_ON";
export const LOADER_OFF = "LOADER_OFF";
export const GET_HEADER_LIST = "GET_HEADER_LIST";
export const GET_FILTER_HEADER_LIST = "GET_FILTER_HEADER_LIST";
export const GET_ROW_LIST = "GET_ROW_LIST";
export const GET_WORKFLOW_LIST = "GET_WORKFLOW_LIST";
export const GET_ROW_DETAILS = "GET_ROW_DETAILS";
export const MAPPING_DATA = "MAPPING_DATA";
export const VISIBLE_REPORT_LIST = "VISIBLE_REPORT_LIST";
export const VISIBLE_REPORT_ROW_LIST = "VISIBLE_REPORT_ROW_LIST";
export const VISIBLE_REPORT_LIST_FILTER = "VISIBLE_REPORT_LIST_FILTER";

export const VISIBLE_LISTOFREPORT = "VISIBLE_LISTOFREPORT";
export const LOGIN = "LOGIN";
export const ERROR ="ERROR";

export const GET_MY_ITEM ="GET_MY_ITEM";
export const GET_MY_SUB_ITEM ="GET_MY_SUB_ITEM";

export const GET_PROFILE_PIC = "GET_PROFILE_PIC";
export const GET_ALL_CHART_VALUE ="GET_ALL_CHART_VALUE";
export const GET_ALL_CHART_REPORT_VALUE ="GET_ALL_CHART_REPORT_VALUE";
export const GET_LOCAL_LOGO ="GET_LOCAL_LOGO";
export const GET_LOCAL_BACKGROUND ="GET_LOCAL_BACKGROUND";

export const GET_CHART_VALUE ="GET_CHART_VALUE";
export const REDIRECT_LOGIN ="REDIRECT_LOGIN";

