export default myWorkConstants = {
  MY_WORK_API: "jobs/candidates",
  MY_WORK_SAGA: "MY_WORK_SAGA",
  MY_WORK_REQUEST: "MY_WORK_REQUEST",
  MY_WORK_RESPONSE: "MY_WORK_RESPONSE",

  MY_WORK_DESCRIPTION_API: "/jobs/candidates/",
  MY_WORK_DESCRIPTION_SAGA: "MY_WORK_DESCRIPTION_SAGA",
  MY_WORK_DESCRIPTION_REQUEST: "MY_WORK_DESCRIPTION_REQUEST",
  MY_WORK_DESCRIPTION_RESPONSE: "MY_WORK_DESCRIPTION_RESPONSE",

  START_WORK_API: "jobs/candidates/jobID/start-work",
  SUBMIT_WORK_API: "jobs/candidates/jobID/submit-work",

  
  MY_WORK_EARNING_STATS_API: "/jobs/candidates/earnings/stats",
  MY_WORK_EARNING_STATS_SAGA: "MY_WORK_EARNING_STATS_SAGA",
  MY_WORK_EARNING_STATS_REQUEST: "MY_WORK_EARNING_STATS_REQUEST",
  MY_WORK_EARNING_STATS_RESPONSE: "MY_WORK_EARNING_STATS_RESPONSE",

  
  MY_WORK_STATS_API: "/jobs/candidates/stats",
  MY_WORK_STATS_SAGA: "MY_WORK_STATS_SAGA",
  MY_WORK_STATS_REQUEST: "MY_WORK_STATS_REQUEST",
  MY_WORK_STATS_RESPONSE: "MY_WORK_STATS_RESPONSE",

  MY_MODULE_DATA_API: "/clients/clientId/modules",
  MY_MODULE_DATA_SAGA: "MY_MODULE_DATA_SAGA",
  MY_MODULE_DATA_REQUEST: "MY_MODULE_DATA_REQUEST",
  MY_MODULE_DATA_RESPONSE: "MY_MODULE_DATA_RESPONSE",
  
  SET_ACTIVE_JOB_ID:"SET_ACTIVE_JOB_ID"
};
