export const dashboardConstants = {  
    //stats
    DASHBOARD_STATS_SAGA: "DASHBOARD_STATS_SAGA",
    DASHBOARD_STATS_REQUEST: "DASHBOARD_STATS_REQUEST",
    DASHBOARD_STATS_RESPONSE: "DASHBOARD_STATS_RESPONSE",
    DASHBOARD_STATS_API: "/vendor/dashboard/stats",
  
    //Users chart Stats
    DASHBOARD_USERS_STATS_SAGA: "DASHBOARD_USERS_STATS_SAGA",
    DASHBOARD_USERS_STATS_REQUEST: "DASHBOARD_USERS_STATS_REQUEST",
    DASHBOARD_USERS_STATS_RESPONSE: "DASHBOARD_USERS_STATS_RESPONSE",
    DASHBOARD_USERS_STATS_API: "/vendor/user-stats",
  
    //Job chart Stats
    DASHBOARD_JOBS_STATS_SAGA: "DASHBOARD_JOBS_STATS_SAGA",
    DASHBOARD_JOBS_STATS_REQUEST: "DASHBOARD_JOBS_STATS_REQUEST",
    DASHBOARD_JOBS_STATS_RESPONSE: "DASHBOARD_JOBS_STATS_RESPONSE",
    DASHBOARD_JOBS_STATS_API: "/vendor/job-stats",
  };
  