export const earningConstants = {
  EARNINGS_SAGA: "EARNINGS_SAGA",
  EARNINGS_REQUEST: "EARNINGS_REQUEST",
  EARNINGS_RESPONSE: "EARNINGS_RESPONSE",
  EARNINGS_API: "jobs/candidates",
  STATS_EARNINGS_SAGA: "STATS_EARNINGS_SAGA",
  STATS_EARNINGS_REQUEST: "STATS_EARNINGS_REQUEST",
  STATS_EARNINGS_RESPONSE: "STATS_EARNINGS_RESPONSE",
  STATS_EARNINGS_STATS_API: "/jobs/candidates/dashboard/stats",
};
