const ScreenConstants = {
  USER: 'USER_SCREEN',

  HOME: 'HOME_SCREEN',
  OVERVIEW: 'OVERVIEW_SCREEN',

  PROPERTIES: 'PROPERTIES_SCREEN',
  PROPERTY_LIST: 'PROPERTY_LIST_SCREEN',
  PROPERTY_DETAIL: 'PROPERTY_DETAIL_SCREEN',
  PROPERTY_CREATE: 'PROPERTY_CREATE_SCREEN',

  PROFILE: 'Profile',
  EDIT_PROFILE: 'Edit Profile',

  REQUIREMENT_DETAIL: 'REQUIREMENT_DETAIL',

  REQUIREMENT_MATCH: 'REQUIREMENT_MATCH',

  LOGIN: 'LOGIN_SCREEN',
  SIGNUP: 'SIGNUP_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  DRAWER_NAVIGATOR: 'DRAWER_NAVIGATOR',

  DASHBOARD: 'DASHBOARD_SCREEN',
  FILTER: 'Filter',
  SEARCH_JOB_SCREEN: 'SEARCH_JOB_SCREEN',
  APPLIED_JOB_LIST: 'APPLIED_JOB_SCREEN',
  JOB_DESCRIPTION: 'Job Description',
  MY_WORK: 'MY_WORK_SCREEN',
  MY_EARNINGS: 'MY_EARNINGS',
  NOTIFICATION_LIST: 'Notification',
  REPORT: 'REPORT_SCREEN',
  FAQ: 'FAQ_SCREEN',
  RAISED_DISPUTE: 'RAISED_DISPUTE_SCREEN',
  RAISED_DISPUTE_DESCRIPTION: 'Dispute Status',
  RAISE_DISPUTE_FORM: 'Raise Dispute Form',
  ASK_US: 'ASK_US_SCREEN',
  WORK_DETAIL: 'Work Details',
  SUB_MODULE_LIST: 'Sub Module List',
  MODULE_DETAIL: 'Module Detail',
  SCREEN_BUILDER: 'SCREEN BUILDER',
  EDIT_MODULE: 'Edit Module',
  ADD_MODULE: 'Add Module',
  MY_JOB_DESCRIPTION: 'Applied job description',
  USER_SELECTION_SCREEN: 'User Selection',
};

export {ScreenConstants};
