import { createSlice } from '@reduxjs/toolkit'

var initialState = {
    pageNumber: 0,
    pageSize: 10,
    totalElements: 0,
    totalPages: 0,
    size: 0,
    loading:0,
    vendorList: [],
    vendorDetails: {},
    vendorTableHeader: [
        { key: 'vendorName', name: 'Vendor Name', hasSorting: false },
        { key: 'vendorRefNo', name: 'Vendor Ref No.', hasSorting: false },
        {
            key: 'skills',
            name: 'Skills',
            hasSorting: false,
            multiChipView: true,
        },
        { key: 'state', name: 'State', hasSorting: true },

        { key: 'status', name: 'Status' },
        { key: 'joinedAt', name: 'Date of Joining' },
        { key: 'actionHeader', icon: 'more_vert' },
    ],
    vendorFilterDetails: {
        vendorName: '',
        vendorRefNo: '',
        status: '',
        skills: '',
        from: null,
        to: null,
    },
    sortOptions: {
        direction: 'DESC',
        sortBy: '',
    },
    activeStep: 0,
    bankMaster: [
        'Abhyudaya Cooperative Bank',
        'Ahmedabad Mercantile Cooperative Bank',
        'Ahmednagar Merchants Cooperative Bank Limited',
        'Airtel Payments Bank Limited',
        'Akola Janata Commercial Cooperative Bank',
        'Allahabad Bank',
        'Almora Urban Cooperative Bank Limited',
        'Ambarnath Jaihind Cooperative Bank Limited, Ambarnath',
        'Andhra Bank',
        'Andhra Pradesh Grameena Vikas Bank',
        'Andhra Pragathi Grameena Bank',
        'Apna Sahakari Bank Limited',
        'Arvind Sahakari Bank Ltd',
        'AU Small Finance Bank Limited',
        'Australia and New Zealand Banking Group Limited',
        'Axis Bank',
        'Bandhan Bank Limited',
        'Bank of America',
        'Bank of Bahrein and Kuwait',
        'Bank of Baroda',
        'Bank of Ceylon',
        'Bank of India',
        'Bank of Maharashtra',
        'Barclays Bank',
        'Bassein Catholic Cooperative Bank Limited',
        'Bhagini Nivedita Sahakari Bank Limited, Pune',
        'Bharat Cooperative Bank Mumbai Limited',
        'BNP Paribas Bank',
        'Bombay Mercantile Cooperative Bank Ltd',
        'Canara Bank',
        'Capital Small Finance Bank Limited',
        'Central Bank of India',
        'CITI Bank',
        'Citizencredit Cooperative Bank Limited',
        'City Union Bank Limited',
        'Coastal Local Area Bank Ltd',
        'Corporation Bank',
        'Credit Agricole Corporate and Investment Bank',
        'Credit Suisse AG',
        'CSB Bank Limited',
        'CTBC Bank Co Limited',
        'DBS Bank India Limited',
        'DCB Bank Limited',
        'Dena Bank',
        'Deogiri Nagari Sahakari Bank Limited, Aurangabad',
        'Deposit Insurance and Credit Guarantee Corporation',
        'Deustche Bank',
        'Dhanalakshmi Bank',
        'DMK Jaoli Bank',
        'Doha Bank QSC',
        'Dombivli Nagari Sahakari Bank Limited',
        'Durgapur Steel Peoples Cooperative Bank Limited',
        'Emirates NBD Bank P J S C',
        'Equitas Small Finance Bank Limited',
        'Esaf Small Finance Bank Limited',
        'Export Import Bank of India',
        'Federal Bank',
        'Fincare Small Finance Bank Limited',
        'FINO Payments Bank',
        'First Abu Dhabi Bank PJSC',
        'Firstrand Bank Limited',
        'G P Parsik Bank',
        'GS Mahanagar Cooperative Bank Limited, Mumbai',
        'Haryana State Cooperative Bank',
        'HDFC Bank',
        'Himachal Pradesh State Cooperative Bank Limited',
        'HSBC Bank',
        'ICICI Bank Limited',
        'IDBI Bank',
        'IDFC First Bank Limited',
        'Idukki District Cooperative Bank Limited',
        'India Post Payment Bank',
        'Indian Bank',
        'Indian Overseas Bank',
        'Indusind Bank',
        'Industrial and Commercial Bank of China Limited',
        'Industrial Bank of Korea',
        'IOB',
        'IOB',
        'Irinjalakuda Town Cooperative Bank Limited',
        'Jalgaon Janata Sahkari Bank Limited',
        'Jammu and Kashmir Bank Limited',
        'Jana Small Finance Bank Limited',
        'Janakalyan Sahakari Bank Limited',
        'Janaseva Sahakari Bank (Borivli) Limited',
        'Janaseva Sahakari Bank Limited',
        'Janata Sahakari Bank Limited (Pune)',
        'Janatha Seva Cooperative Bank Ltd',
        'Jio Payments Bank Limited',
        'JP Morgan Chase Bank NA',
        'Kallappanna Awade Ichalkaranji Janata Sahakari Bank Limited',
        'Kalupur Commercial Cooperative Bank',
        'Kalyan Janata Sahakari Bank Limited',
        'Karnataka Bank Limited',
        'Karnataka Gramin Bank',
        'Karnataka Vikas Grameena Bank',
        'Karur Vysya Bank',
        'KEB Hana Bank',
        'Kerala Gramin Bank',
        'Kookmin Bank',
        'Kotak Mahindra Bank Limited',
        'Kozhikode District Cooperative Bank Limited',
        'Krung Thai Bank PCL',
        'Laxmi Vilas Bank',
        'Maharashtra Gramin Bank',
        'Maharashtra State Cooperative Bank',
        'Mahesh Sahakari Bank Limited Pune',
        'MashreqBank PSC',
        'Mizuho Bank Limited',
        'Model Co-operative Bank Ltd',
        'MUFG Bank Limited',
        'Nagar Urban Cooperative Bank',
        'Nagpur Nagarik Sahakari Bank Limited',
        'National Bank for Agriculture and Rural Development',
        'Nav Jeevan Cooperative Bank Limited',
        'New India Cooperative Ban Limited',
        'NKGSB Cooperative Bank Limited',
        'North East Small Finance Bank Limited',
        'NSDL Payments Bank Limited',
        'Nutan Nagarik Sahakari Bank Limited',
        'Oriental Bank of Commerce',
        'Paytm Payments Bank Limited',
        'Prime Cooperative Bank Limited',
        'PT Bank Maybank Indonesia TBK',
        'Punjab and Maharashtra Cooperative Bank Limited',
        'Punjab and Sind Bank',
        'Punjab National Bank',
        'Qatar National Bank SAQ',
        'Rabobank International',
        'Rajarambapu Sahakari Bank Limited',
        'Rajarshi Shahu Sahakari Bank Limited, Pune',
        'Rajasthan Marudhara Gramin Bank',
        'Rajgurunagar Sahakari Bank Limited',
        'Rajkot Nagarik Sahakari Bank Limited',
        'Rajnandgaon District Central Co-operative Bank Ltd',
        'RBL Bank Limited',
        'Reserve Bank of India',
        'Sahebrao Deshmukh Cooperative Bank Limited',
        'Samarth Sahakari Bank Limited',
        'Sant Sopankaka Sahakari Bank Limited',
        'Saraspur Nagrik Cooperative Bank Limited, Saraspur',
        'Saraswat Cooperative Bank Limited',
        'Satara Sahakari Bank Limited',
        'SBER Bank',
        'SBM Bank India Limited',
        'Shikshak Sahakari Bank Limited',
        'Shinhan Bank',
        'Shivalik Mercantile Cooperative Bank Limited',
        'Shri Chhatrapati Rajashri Shahu Urban Cooperative Bank Limited',
        'Shri Veershaiv Cooperative Bank Limited',
        'Sir M Visvesvaraya Cooperative Bank Limited',
        'Societe Generale',
        'Solapur Janata Sahkari Bank Limited',
        'South Indian Bank',
        'Sree Charan Souhardha Co Operative Bank Ltd',
        'Standard Chartered Bank',
        'State Bank of India',
        'Suco Souharda Sahakari Bank Limited',
        'Sumitomo Mitsui Banking Corporation',
        'Surat National Cooperative Bank Limited',
        'Suryoday Small Finance Bank Limited',
        'Sutex Cooperative Bank Limited',
        'Syndicate Bank',
        'Tamilnad Mercantile Bank Limited',
        'Telangana State Coop Apex Bank',
        'Textile Traders Cooperative Bank Limited',
        'The A.P. Mahesh Cooperative Urban Bank Limited',
        'The Ahmednagar District Central Co-Operative Bank Ltd',
        'The Ajara Urban Cooperative Bank Limited, Ajara',
        'The Akola District Central Cooperative Bank',
        'The Andhra Pradesh State Coop Bank Limited',
        'The Banaskantha Mercantile Cooperative Bank Ltd',
        'The Bank of Nova Scotia',
        'The Baramati Sahakari Bank Limited',
        'The Cosmos Cooperative Bank Limited',
        'The Delhi State Cooperative Bank Limited',
        'The Gadchiroli District Central Cooperative Bank Limited',
        'The Greater Bombay Cooperative Bank Limited',
        'The Gujarat State Cooperative Bank Limited',
        'The HASTI Cooperative Bank Limited',
        'The Jalgaon Peoples Cooperative Bank',
        'The Kangra Central Cooperative Bank Limited',
        'The Kangra Cooperative Bank Limited',
        'The Karad Urban Cooperative Bank Limited',
        'The Karanataka State Cooperative Apex Bank Limited',
        'The Kerala State Cooperative Bank Limited',
        'The Kolhapur Urban Co-op Bank Ltd',
        'The Kurmanchal Nagar Sahkari Bank Limited',
        'The Malad Sahakari Bank Ltd',
        'The Malkapur Urban Cooperative Bank Limited, Malkapur',
        'The Mehsana Urban Cooperative Bank Limited',
        'The Mumbai District Central Cooperative Bank Limited',
        'The Municipal Cooperative Bank Limited, Mumbai',
        'The Muslim Cooperative Bank Limited',
        'The Nainital Bank Limited',
        'The Nasik Merchants Cooperative Bank Limited',
        'The Navnirman Cooperative Bank Limited',
        'The Nawanagar Cooperative Bank Ltd',
        'The Nilambur Cooperative Urban Bank Limited, Nilambur',
        'The Odisha State Cooperative Bank Limited',
        'The Pandharpur Urban Cooperative Bank Limited, Pandharpur',
        'The Punjab State Cooperative Bank Ltd',
        'The Pusad Urban Cooperative Bank Limited, Pusad',
        'The Rajasthan State Cooperative Bank Limited',
        'The Seva Vikas Cooperative Bank Limited',
        'The Shamrao Vithal Cooperative Bank Limited',
        'The Sindhudurg District Central Coop Bank Limited',
        'The Surat District Cooperative Bank Limited',
        'The Surath Peoples Cooperative Bank Limited',
        'The Tamilnadu State Apex Cooperative Bank',
        'The Thane Bharat Sahakari Bank Limited',
        'The Thane District Central Cooperative Bank Limited',
        'The Udaipur Urban Cooperative Bank Limited',
        'The Urban Cooperative Bank Limited',
        'The Varachha Cooperative Bank Limited',
        'The Vijay Cooperative Bank Limited',
        'The Vishweshwar Sahakari Bank Limited',
        'The West Bengal State Cooperative Bank Limited',
        'The Zoroastrian Cooperative Bank Limited',
        'Thrissur District Cooperative Bank Limited',
        'TJSB Sahakari Bank Limited',
        'Tumkur Grain Merchants Cooperative Bank Limited',
        'UCO Bank',
        'Ujjivan Small Finance Bank Limited',
        'Union Bank of India',
        'United Bank of India',
        'United Overseas Bank',
        'Utkarsh Small Finance Bank',
        'Uttar Pradesh Cooperative Bank Limited',
        'Vasai Janata Sahakari Bank Limited',
        'Vasai Vikas Sahakari Bank Limited',
        'Vijaya Bank',
        'Woori Bank',
        'Yes Bank',
        'Zila Sahkari Bank Limited Ghaziabad',
    ],
    showVendorDetailsPopup: false,
    vendorCredential: {},
    vendorEmailTemplate: {},
    vendorStats: {},
}

const vendorManagementSlice = createSlice({
    name: 'vendorManagement',
    initialState,
    reducers: {
        setVendorDetailFilter(state, { type, payload }) {
            state.vendorFilterDetails = payload
        },
        setVendorList(state, { type, payload }) {
            const { list, totalElements, totalPages, size } = payload
            state.vendorList = list
            state.totalElements = totalElements
            state.totalPages = totalPages
            state.size = size
        },
        setLoader(state, { type, payload }) {
            state.loading = payload
        },
        setVendorDetails(state, { type, payload }) {
            state.vendorDetails = payload
        },
        setVendorFormBtnState(state, { type, payload }) {
            const { name, value } = payload
            state[name] = value
        },
        setShowVendorDetailsPopup(state, action) {
            state.showVendorDetailsPopup = action.payload
        },
        setVendorCredential(state, action) {
            state.vendorCredential = action.payload
        },
        setVendorEmailTemplate(state, action) {
            state.vendorEmailTemplate = action.payload
        },
        setVendorStats(state, action) {
            state.vendorStats = action.payload
        },
    },
})

export default vendorManagementSlice.reducer

// Actions

export const {
    setVendorList,
    setVendorDetailFilter,
    setLoader,
    setVendorDetails,
    setVendorFormBtnState,
    setShowVendorDetailsPopup,
    setShowVendorCredential,
    setVendorCredential,
    setVendorEmailTemplate,
    setVendorStats,
} = vendorManagementSlice.actions
