export const jobManagementConstants = {
  VENDER_JOB_LIST_SAGA: "VENDER_JOB_LIST_SAGA",
  VENDER_JOB_LIST_REQUEST: "VENDER_JOB_LIST_REQUEST",
  VENDER_JOB_LIST_RESPONSE: "VENDER_JOB_LIST_RESPONSE",
  VENDER_JOB_LIST_API: "/jobs/",

  SKILLS_LIST_SAGA: "SKILLS_LIST_SAGA",
  SKILLS_LIST_REQUEST: "SKILLS_LIST_REQUEST",
  SKILLS_LIST_RESPONSE: "SKILLS_LIST_RESPONSE",
  SKILLS_LIST_API: "/skill/skills",

  SKILLS_CATEGORIES_LIST_SAGA: "SKILLS_CATEGORIES_LIST_SAGA",
  SKILLS_CATEGORIES_LIST_REQUEST: "SKILLS_CATEGORIES_LIST_REQUEST",
  SKILLS_CATEGORIES_LIST_RESPONSE: "SKILLS_CATEGORIES_LIST_RESPONSE",
  SKILLS_CATEGORIES_LIST_API: "/skill/skillsCategories",

  JOB_DESCRIPTION_SAGA: "JOB_DESCRIPTION_SAGA",
  JOB_DESCRIPTION_REQUEST: "JOB_DESCRIPTION_REQUEST",
  JOB_DESCRIPTION_RESPONSE: "JOB_DESCRIPTION_RESPONSE",
  JOB_DESCRIPTION_API: "/jobs/id",

  APPLY_JOB_API: "/jobs/jobID/apply",

  UNAPPLY_JOB_API: "/jobs/jobID/unapply",
};
