export const myWorkConstants = {
  MY_WORK_SAGA: "MY_WORK_SAGA",
  MY_WORK_REQUEST: "MY_WORK_REQUEST",
  MY_WORK_RESPONSE: "MY_WORK_RESPONSE",
  MY_WORK_API: "/jobs/candidates",

  MY_WORK_DETAILS_SAGA: "MY_WORK_DETAILS_SAGA",
  MY_WORK_DETAILS_REQUEST: "MY_WORK_DETAILS_REQUEST",
  MY_WORK_DETAILS_RESPONSE: "MY_WORK_DETAILS_RESPONSE",
  MY_WORK_DETAILS_API: "/jobs/candidates/jobid",

  START_MY_WORK_API: "/jobs/candidates/candidatesID/start-work",
  SUBMIT_MY_WORK_API: "/jobs/candidates/candidatesID/submit-work",
  ASSIGN_JOB_TO_API:
    "/jobs/candidates/candidateID/assign",
  TOGGLE_ASSIGN_JOB_MODAL: "TOGGLE_ASSIGN_JOB_MODAL",

  SCREEN_BUILDER_MODULES_SAGA: "SCREEN_BUILDER_MODULES_SAGA",
  SCREEN_BUILDER_MODULES_REQUEST: "SCREEN_BUILDER_MODULES_REQUEST",
  SCREEN_BUILDER_MODULES_RESPONSE: "SCREEN_BUILDER_MODULES_RESPONSE",
  SCREEN_BUILDER_MODULES_API: "clients/clientid/modules?page=0&size=10&sortOrder=DESC",

  SET_ACTIVE_JOB_ID:"SET_ACTIVE_JOB_ID"
};
