export const searchJobConstants = {
  SEARCH_JOB_API: "jobs/",
  SEARCH_JOB_SAGA: "SEARCH_JOB_SAGA",
  SEARCH_JOB_REQUEST: "SEARCH_JOB_REQUEST",
  SEARCH_JOB_RESPONSE: "SEARCH_JOB_RESPONSE",

  SEARCH_JOB_DESCRIPTION_API: "jobs",
  SEARCH_JOB_DESCRIPTION_SAGA: "SEARCH_JOB_DESCRIPTION_SAGA",
  SEARCH_JOB_DESCRIPTION_REQUEST: "SEARCH_JOB_DESCRIPTION_REQUEST",
  SEARCH_JOB_DESCRIPTION_RESPONSE: "SEARCH_JOB_DESCRIPTION_RESPONSE",

  APPLY_JOB_API: "jobs/jobID/apply?userNote=UserNote",
  APPLY_JOB_SAGA: "APPLY_JOB_SAGA",
  APPLY_JOB_REQUEST: "APPLY_JOB_REQUEST",
  APPLY_JOB_RESPONSE: "APPLY_JOB_RESPONSE",

  SIMILAR_JOB_API: "jobs",
  SIMILAR_JOB_SAGA: "SIMILAR_JOB_SAGA",
  SIMILAR_JOB_REQUEST: "SIMILAR_JOB_REQUEST",
  SIMILAR_JOB_RESPONSE: "SIMILAR_JOB_RESPONSE",

  OTHER_OPENING_JOB_API: "jobs",
  OTHER_OPENING_JOB_SAGA: "OTHER_OPENING_JOB_SAGA",
  OTHER_OPENING_JOB_REQUEST: "OTHER_OPENING_JOB_REQUEST",
  OTHER_OPENING_JOB_RESPONSE: "OTHER_OPENING_JOB_RESPONSE",

  SKILLS_API: "skill/skills",
  SKILLS_SAGA: "SKILLS_SAGA",
  SKILLS_REQUEST: "SKILLS_REQUEST",
  SKILLS_RESPONSE: "SKILLS_RESPONSE",

  SKILL_CATEGORIES_API: "skill/skillsCategories",
  SKILL_CATEGORIES_SAGA: "SKILL_CATEGORIES_SAGA",
  SKILL_CATEGORIES_REQUEST: "SKILL_CATEGORIES_REQUEST",
  SKILL_CATEGORIES_RESPONSE: "SKILL_CATEGORIES_RESPONSE",

  UPDATE_FILTER_DATA: "UPDATE_FILTER_DATA",
  RESET_FILTER_DATA: "RESET_FILTER_DATA",

  UPDATE_PAGE: "UPDATE_PAGE",

  SET_FILTER_COLOR: "SET_FILTER_COLOR"
};
