export const commonConstants = {
  GLOBAL_RESET_TOAST_DATA: "GLOBAL_RESET_TOAST_DATA",
  GLOBAL_SET_TOAST_DATA: "GLOBAL_SET_TOAST_DATA",
  GLOBAL_LOADER_DATA: "GLOBAL_LOADER_DATA",
  BLOGS_API: "v1/blogs/educational",
  BLOGS_SAGA: "BLOGS_SAGA",
  BLOGS_REQUEST: "BLOGS_REQUEST",
  BLOGS_RESPONSE: "BLOGS_RESPONSE",
};
