export const disputeConstants = {
  DISPUTE_LIST_API: "disputes",
  DISPUTE_LIST_SAGA: "DISPUTE_LIST_SAGA",
  DISPUTE_LIST_REQUEST: "DISPUTE_LIST_REQUEST",
  DISPUTE_LIST_RESPONSE: "DISPUTE_LIST_RESPONSE",

  DISPUTE_LIST_CATEGORIES_API: "disputes/categories",
  DISPUTE_LIST_CATEGORIES_SAGA: "DISPUTE_LIST_CATEGORIES_SAGA",
  DISPUTE_LIST_CATEGORIES_REQUEST: "DISPUTE_LIST_CATEGORIES_REQUEST",
  DISPUTE_LIST_CATEGORIES_RESPONSE: "DISPUTE_LIST_CATEGORIES_RESPONSE",

  CREATE_DISPUTE_API: "disputes",
};
