FROM openjdk:11
#MAINTAINER Bharath Kumar
ADD target/onboarding.jar onboarding.jar
#ENTRYPOINT ["java","-jar","test.jar"]
#WORKDIR /app
#COPY target/onboarding.jar .
CMD ["java", "-jar", "onboarding.jar"]
#ENTRYPOINT ["java", "-jar", "onboarding.jar"]
