export const commonConstants = {
  GLOBAL_RESET_TOAST_DATA: "GLOBAL_RESET_TOAST_DATA",
  GLOBAL_SET_TOAST_DATA: "GLOBAL_SET_TOAST_DATA",

  BLOGS_API: "/v1/blogs/global-news",
  BLOGS_SAGA: "BLOGS_SAGA",
  BLOGS_REQUEST: "BLOGS_REQUEST",
  BLOGS_RESPONSE: "BLOGS_RESPONSE",

  DEVICE_ID_DATA: "DEVICE_ID_DATA",

  RESET_COMMON_DATA: "RESET_COMMON_DATA",

  NOTIFICATION_API: "notifications",
  NOTIFICATION_SAGA: "NOTIFICATION_SAGA",
  NOTIFICATION_REQUEST: "NOTIFICATION_REQUEST",
  NOTIFICATION_RESPONSE: "NOTIFICATION_RESPONSE",

  FAQ_API: "faqs",
  FAQ_SAGA: "FAQ_SAGA",
  FAQ_REQUEST: "FAQ_REQUEST",
  FAQ_RESPONSE: "FAQ_RESPONSE",
};
