FROM openjdk:11
#MAINTAINER Bharath Kumar
ADD target/Auditing-1.0.jar Auditing-1.0.jar
#ENTRYPOINT ["java","-jar","test.jar"]
#WORKDIR /app
#COPY target/onboarding.jar .
CMD ["java", "-jar", "Auditing-1.0.jar"]
#ENTRYPOINT ["java", "-jar", "onboarding.jar"]
