<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Password Changed</title>
</head>
<body>
  <h1>Hello, Password changed successfully! </h1>
  <div> This email includes your account details with new password, Please keep it safe!</div>
   <div style="margin-top: 10px"> Appliaction URL : <a href="url">brandpulse.com</a></b></div>
  <div > ClientId : <b>${credentials.clientId}</b></div>
  <div>  Username : <b>${credentials.clientId}</b></div>
  <div > New Password : <b>${credentials.password}</b></div>
<br>
 <div> Questions? Check out our <b>user guide and Videos</b> or Drop us a line</div>
<div> we are here to help. </div>
</br>
<br/>
<div> Sincerely, </div>
<div> Your brand pulse Team!</div>
</body>
</html>