export const appliedjobConstants = {
  APPLIED_JOBS_SAGA: "APPLIED_JOBS_SAGA",
  APPLIED_JOBS_REQUEST: "APPLIED_JOBS_REQUEST",
  APPLIED_JOBS_RESPONSE: "APPLIED_JOBS_RESPONSE",
  APPLIED_JOBS_API: "/jobs/applied/",

  APPLIED_JOBS_DETAILS_SAGA: "APPLIED_JOBS_DETAILS_SAGA",
  APPLIED_JOBS_DETAILS_REQUEST: "APPLIED_JOBS_DETAILS_REQUEST",
  APPLIED_JOBS_DETAILS_RESPONSE: "APPLIED_JOBS_DETAILS_RESPONSE",
  APPLIED_JOBS_DETAILS_API: "/jobs/applied/jobid",
};
