export const raiseDisputeConstants = {
  RAISE_DISPUTE_LIST_SAGA: "RAISE_DISPUTE_LIST_SAGA",
  RAISE_DISPUTE_LIST_REQUEST: "RAISE_DISPUTE_LIST_REQUEST",
  RAISE_DISPUTE_LIST_RESPONSE: "RAISE_DISPUTE_LIST_RESPONSE",
  RAISE_DISPUTE_LIST_API: "disputes",

  RAISE_DISPUTE_CATEGORIES_SAGA: "RAISE_DISPUTE_CATEGORIES_SAGA",
  RAISE_DISPUTE_CATEGORIES_REQUEST: "RAISE_DISPUTE_CATEGORIES_REQUEST",
  RAISE_DISPUTE_CATEGORIES_RESPONSE: "RAISE_DISPUTE_CATEGORIES_RESPONSE",
  RAISE_DISPUTE_CATEGORIES_API: "disputes/categories",

  CREATE_RAISE__DISPUTE_API: "disputes",
};
