export const dashboardConstants = {
  DASHBOARD_STATS_API: "jobs/candidates/dashboard/stats",
  DASHBOARD_STATS_SAGA: "DASHBOARD_STATS_SAGA",
  DASHBOARD_STATS_REQUEST: "DASHBOARD_STATS_REQUEST",
  DASHBOARD_STATS_RESPONSE: "DASHBOARD_STATS_RESPONSE",
};
