export const manageVendorUserConstants = {
  FETCH_VENDOR_USER_SAGA: "FETCH_VENDOR_USER_SAGA",
  FETCH_VENDOR_USER_REQUEST: "FETCH_VENDOR_USER_REQUEST",
  FETCH_VENDOR_USER_RESPONSE: "FETCH_VENDOR_USER_RESPONSE",
  FETCH_VENDOR_USER_API: "vendor-user/",

  FETCH_VENDOR_USER_DETAILS_SAGA: "FETCH_VENDOR_USER_DETAILS_SAGA",
  FETCH_VENDOR_USER_DETAILS_REQUEST: "FETCH_VENDOR_USER_DETAILS_REQUEST",
  FETCH_VENDOR_USER_DETAILS_RESPONSE: "FETCH_VENDOR_USER_DETAILS_RESPONSE",
  FETCH_VENDOR_USER_DETAILS_API: "vendor-user/id",

  ADD_VENDOR_USER_API: "vendor-user/",

  EDIT_VENDOR_USER_API: "vendor-user/id",

  FETCH_VENDOR_USER_CREDS_SAGA: "FETCH_VENDOR_USER_CREDS_SAGA",
  FETCH_VENDOR_USER_CREDS_REQUEST: "FETCH_VENDOR_USER_CREDS_REQUEST",
  FETCH_VENDOR_USER_CREDS_RESPONSE: "FETCH_VENDOR_USER_CREDS_RESPONSE",
  FETCH_VENDOR_USER_CREDS_API: "vendor-user/id/credentials",

  ACTIVATE_VENDOR_USER_SAGA: "ACTIVATE_VENDOR_USER_SAGA",
  ACTIVATE_VENDOR_USER_REQUEST: "ACTIVATE_VENDOR_USER_REQUEST",
  ACTIVATE_VENDOR_USER_RESPONSE: "ACTIVATE_VENDOR_USER_RESPONSE",
  ACTIVATE_VENDOR_USER_API: "/vendor-user/activate/id",

  DEACTIVATE_VENDOR_USER_SAGA: "DEACTIVATE_VENDOR_USER_SAGA",
  DEACTIVATE_VENDOR_USER_REQUEST: "DEACTIVATE_VENDOR_USER_REQUEST",
  DEACTIVATE_VENDOR_USER_RESPONSE: "DEACTIVATE_VENDOR_USER_RESPONSE",
  DEACTIVATE_VENDOR_USER_API: "/vendor-user/deactivate/id"
};