export const lColors = {
  staticPrimaryColor: "#50bfb7",
  staticTextColor: "#000000",
  staticGrayColor: "gray",
  staticDisableTextColor: "#222222",
  staticShowColor: "#44B4A8",
  staticDisableShowColor: "#565D5B",
  staticProfileDisableShowColor: "#F6F8FA",
  staticWhiteColor: "#FFFFFF",
  staticIconGrayColor: "#B4BAC1",
  staticRedColor: "red",
  staticBlackColor: "black",
  transparentColor: "transparent",
  backgroundColor: "#F5F5F5",
  staticGrayLabelColor: "#00000099",
  componentFrameColor: "#0000001F",
  graphHorizontal: "#9079F8",
  graphVertical: "#4185F4",
  lightGrayColor: "#00000061",
  shadowColor: "#ECECF3",
  grayToWhite: "gray",
  tableHeaderBg: "#FFFFFF",
  tableRowBg: "#EEEEEE",
  buttonlightGrayColor: "#d9d9d9",
  splashScreenColor: "#1981A5"
};
